FROM driftphp/base as extension
RUN apk --no-cache add autoconf build-base
RUN pecl channel-update pecl.php.net
RUN pecl install ev

FROM driftphp/base
COPY --from=extension /usr/local/lib/php/extensions/no-debug-non-zts-20190902/ev.so /usr/local/lib/php/extensions/no-debug-non-zts-20190902/ev.so
RUN docker-php-ext-enable ev
