FROM driftphp/base as extension
RUN apk --no-cache add autoconf build-base libuv-dev
RUN pecl channel-update pecl.php.net
RUN pecl install uv-0.2.4

FROM driftphp/base
RUN apk --no-cache add libuv libuv-dev
COPY --from=extension /usr/local/lib/php/extensions/no-debug-non-zts-20190902/uv.so /usr/local/lib/php/extensions/no-debug-non-zts-20190902/uv.so
RUN docker-php-ext-enable uv
